package hse.group1.focusflow.model.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

public class UserRegistrationDto {

  private Long id; // generated by the server, exposed read‑only

  @NotBlank
  @Email
  private String email;

  @NotBlank
  @Size(min = 10, max = 12)
  private String password; // write‑only (but readable internally via getter)

  @NotBlank
  private String firstName;

  @NotBlank
  private String lastName;

  private Long teamId;

  // Constructors
  public UserRegistrationDto() {}

  public UserRegistrationDto(
    Long id,
    String email,
    String password,
    String firstName,
    String lastName,
    Long teamId
  ) {
    this.id = id;
    this.email = email;
    this.password = password;
    this.firstName = firstName;
    this.lastName = lastName;
    this.teamId = teamId;
  }

  // Getters and Setters

  // Read‑only ID
  public Long getId() {
    return id;
  }

  // Email
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  // Password (write‑only for JSON) but needs getter for internal use
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  // First name
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  // Last name
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  // Team assignment
  public Long getTeamId() {
    return teamId;
  }

  public void setTeamId(Long teamId) {
    this.teamId = teamId;
  }
}
